"""empty message

Revision ID: 6522176a50a5
Revises: 5622fa97f204
Create Date: 2021-02-17 13:43:46.168029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6522176a50a5'
down_revision = '5622fa97f204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmd', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmd')
    # ### end Alembic commands ###
