"""empty message

Revision ID: ff27fdb674d8
Revises: 6522176a50a5
Create Date: 2021-02-17 14:16:06.256794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff27fdb674d8'
down_revision = '6522176a50a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'confirmd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmd', sa.BOOLEAN(), nullable=True))
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
